name: detect-workflow 
on:
  push:
    branches:
      - master
      - main 

jobs:
  tests:
    runs-on: ubuntu-latest
    outputs: 
      env:  ${{steps.filter.output.changes}}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with: 
          filters: |
             backend:
               - 'backend/**'
             frontend:
               - 'frontend/**'
  demo:
    runs-on: ubuntu-latest
    needs:
    - tests
    strategy: 
      matrix:
        env: ${{ (needs.test.outputs.env) }}
    steps:  
      - name: print the message 
        run:  echo " hello all "    