name: detect-workflow 
on:
  push:
    branches:
      - master
      - main 

jobs:
  tests:
    runs-on: ubuntu-latest
    outputs: 
      env:  ${{steps.filter.output.changes}}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/backend/backend-filters.yaml
          list-files: "json"
  demo:
    runs-on: ubuntu-latest
    needs:
    - tests
    strategy: 
      matrix:
        env: ${{ fromJSON(needs.test.outputs.env) }}
    steps:  
      - name: print the message 
        run:  echo " hello all "    