name: detect-workflow 
on:
  push:
    branches:
      - master
      - main 
      
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: backend
  # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: echo "hello world"

