name: detect-workflow 
on:
  push:
    branches:
      - master
      - main 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: get the code 
        uses: actions/checkout@v3
      - name: detect the changes   
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
    # run only if 'backend' files were changed
      - name: backend tests
        if: steps.filter.outputs.backend == 'true'
      - name: print message   
        run: echo "hello-world" 

    # run only if 'frontend' files were changed
      - name: frontend tests
        if: steps.filter.outputs.frontend == 'true'
        run: echo "hello-world"  

    # run if 'backend' or 'frontend' files were changed
      - name: e2e tests
        if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.frontend == 'true'
        run: echo "this is detected"

