name: Promote to Latest Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version tag to promote to latest (e.g., v1.1.3)"
        required: true

jobs:
  promote:
    name: Promote selected version to latest tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Promote version to latest using EndBug/latest-tag
        uses: EndBug/latest-tag@v1
        with:
          tag: ${{ github.event.inputs.version }}
